config/routes.rb
BootstrapStarter::Application.routes.draw do

  resources :statuses

  resources :violation_types

  resources :categories

  resources :election_precinct_numbers

  resources :election_district_names

  resources :complaints

  match '/move_to_higher_level/:id', :to => 'complaints#move_to_higher_level', :as => :move_to_higher_level, :via => :get

  match '/unlink/:file_id', :to => 'complaints#unlink', :as => :unlink, :via => :get

  resources :cec_form_children

  resources :cec_forms

  resources :dec_form_children

  resources :dec_forms

  resources :pec_forms

  resources :complaints

	namespace :admin do
		resources :users
	end
	match '/admin', :to => 'admin#index', :as => :admin, :via => :get

	devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

	root :to => 'root#index'

	match '', :to => redirect("/") # handles /
	match '*path', :to => redirect("/") # handles /not-a-locale/anything

end

app/controllers/violation_types_controller.rb
class ViolationTypesController < ApplicationController
  before_filter :authenticate_user!
  # GET /violation_types
  # GET /violation_types.json
  def index
    @violation_types = ViolationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @violation_types }
    end
  end

  # GET /violation_types/1
  # GET /violation_types/1.json
  def show
    @violation_type = ViolationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @violation_type }
    end
  end

  # GET /violation_types/new
  # GET /violation_types/new.json
  def new
    @violation_type = ViolationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @violation_type }
    end
  end

  # GET /violation_types/1/edit
  def edit
    @violation_type = ViolationType.find(params[:id])
  end

  # POST /violation_types
  # POST /violation_types.json
  def create
    @violation_type = ViolationType.new(params[:violation_type])

    respond_to do |format|
      if @violation_type.save
        format.html { redirect_to @violation_type, notice: I18n.t('violation_type.notice.create') }
        format.json { render json: @violation_type, status: :created, location: @violation_type }
      else
        format.html { render action: "new" }
        format.json { render json: @violation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /violation_types/1
  # PUT /violation_types/1.json
  def update
    @violation_type = ViolationType.find(params[:id])

    respond_to do |format|
      if @violation_type.update_attributes(params[:violation_type])
        format.html { redirect_to @violation_type, notice: I18n.t('violation_type.notice.update') }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @violation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violation_types/1
  # DELETE /violation_types/1.json
  def destroy
    @violation_type = ViolationType.find(params[:id])
    @violation_type.destroy

    respond_to do |format|
      format.html { redirect_to violation_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/violation_types_helper.rb
module ViolationTypesHelper
end

app/views/violation_types/_form.html.erb
<%= semantic_form_for @violation_type do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/violation_types/edit.html.erb
<h1>Editing violation_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @violation_type %> |
<%= link_to 'Back', violation_types_path %>

app/views/violation_types/index.html.erb
<h1>Listing violation_types</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @violation_types.each do |violation_type| %>
  <tr>
    <td><%= violation_type.title %></td>
    <td><%= link_to 'Show', violation_type %></td>
    <td><%= link_to 'Edit', edit_violation_type_path(violation_type) %></td>
    <td><%= link_to 'Destroy', violation_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Violation type', new_violation_type_path %>

app/views/violation_types/new.html.erb
<h1>New violation_type</h1>

<%= render 'form' %>

<%= link_to 'Back', violation_types_path %>

app/views/violation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @violation_type.title %>
</p>


<%= link_to 'Edit', edit_violation_type_path(@violation_type) %> |
<%= link_to 'Back', violation_types_path %>