config/routes.rb
BootstrapStarter::Application.routes.draw do

  resources :statuses

  resources :violation_types

  resources :categories

  resources :election_precinct_numbers

  resources :election_district_names

  resources :complaints

  match '/move_to_higher_level/:id', :to => 'complaints#move_to_higher_level', :as => :move_to_higher_level, :via => :get

  match '/unlink/:file_id', :to => 'complaints#unlink', :as => :unlink, :via => :get

  resources :cec_form_children

  resources :cec_forms

  resources :dec_form_children

  resources :dec_forms

  resources :pec_forms

  resources :complaints

	namespace :admin do
		resources :users
	end
	match '/admin', :to => 'admin#index', :as => :admin, :via => :get

	devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

	root :to => 'root#index'

	match '', :to => redirect("/") # handles /
	match '*path', :to => redirect("/") # handles /not-a-locale/anything

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_filter :authenticate_user!

  def index
    @latest_complaint = Complaint.last if user_signed_in?
  end


end

app/views/root/index.html.erb
<div class="row">


	<div class="span2 complaints">
    <div class="complaints_header">
      <strong>საჩივრები</strong>
    </div>
    <div class="clear">
      <%= link_to 'ახალი საჩივარი', new_complaint_path %>
    </div>
    <div class="clear">
      <%= link_to 'საჩივრები', complaints_path %>
    </div>
    <div class="clear">
      <% if @latest_complaint %>
         <%= link_to 'უახლესი საჩივარი', complaint_path(@latest_complaint) %>
      <% end %>
    </div>

	</div>


	<div class="span9 observations">
	   <div class="observations_header">
	      <strong>დაკვირვებები</strong>
	   </div>
      <div class="clear">
         <%= link_to 'ახალი PEC', new_pec_form_path %>
      </div>
      <div class="clear">
         <%= link_to 'PEC საჩივრების სტატისტიკა', pec_forms_path %>
      </div>



	   <div class="clear">
         <%= link_to 'ახალი DEC', new_dec_form_path %>
      </div>
      <div class="clear">
         <%= link_to 'DEC საჩივრების სტატისტიკა', dec_forms_path %>
      </div>



	   <div class="clear">
         <%= link_to 'ახალი CEC', new_cec_form_path %>
      </div>
      <div class="clear">
         <%= link_to 'CEC საჩივრების სტატისტიკა', cec_forms_path %>
      </div>
	</div>
</div>